<a href="https://colab.research.google.com/github/jeraldflowers/Linear-Algebra-Fundamentals/blob/main/diagonal_matrix_simetric_and_properties.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [3]:
vector = np.array([1,2,3,4,5])

matrix = np.diag(vector)

print(matrix)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [4]:
print(matrix[0:4, 0:3])

[[1 0 0]
 [0 2 0]
 [0 0 3]
 [0 0 0]]


In [6]:
print(matrix[0:3, 0:4])

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]]


In [7]:
A = np.diag([2,3,4,5])
print(A)

[[2 0 0 0]
 [0 3 0 0]
 [0 0 4 0]
 [0 0 0 5]]


In [8]:
v1 = np.array([1,1,1,1])

print(v1)

print(A.dot(v1.T))

[1 1 1 1]
[2 3 4 5]


In [9]:
A_inv = np.diag([1/2, 1/3, 1/4, 1/5])
print(A_inv)

[[0.5        0.         0.         0.        ]
 [0.         0.33333333 0.         0.        ]
 [0.         0.         0.25       0.        ]
 [0.         0.         0.         0.2       ]]


In [11]:
identity = A.dot(A_inv)

print(identity)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [12]:
A_inv_calc = np.linalg.inv(A)
print(A_inv_calc)

[[0.5        0.         0.         0.        ]
 [0.         0.33333333 0.         0.        ]
 [0.         0.         0.25       0.        ]
 [0.         0.         0.         0.2       ]]


In [14]:
print(A.T)
print(A)

[[2 0 0 0]
 [0 3 0 0]
 [0 0 4 0]
 [0 0 0 5]]
[[2 0 0 0]
 [0 3 0 0]
 [0 0 4 0]
 [0 0 0 5]]


In [15]:
simetric = np.array([[1,2,3],
                     [2,-1,7],
                     [3,7,11]])
print(simetric)

[[ 1  2  3]
 [ 2 -1  7]
 [ 3  7 11]]


In [16]:
print(simetric.T)

[[ 1  2  3]
 [ 2 -1  7]
 [ 3  7 11]]
