<a href="https://colab.research.google.com/github/jeraldflowers/Linear-Algebra-Fundamentals/blob/main/dimension_vector_matrix_tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
escalar = 5.679
vector = np.array([1,2,3])
matrix = np.array([[1,2], [3,4]])
tensor = np.array([
    [[1,2,3],[4,5,6],[7,8,9]],
    [[10,11,12],[13,14,15],[16,17,18]],
    [[19,20,21],[22,23,24],[25,26,27]]
])

In [3]:
print(tensor)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


In [4]:
matrix.shape

(2, 2)

In [5]:
tensor.shape

(3, 3, 3)

In [6]:
vector.shape

(3,)

In [7]:
len(vector)

3

In [8]:
len(matrix)

2

In [9]:
len(tensor)

3

In [10]:
print(matrix.size)

4


In [11]:
print(tensor.size)

27
