<a href="https://colab.research.google.com/github/jeraldflowers/Linear-Algebra-Fundamentals/blob/main/inner_product_properties.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
A = np.array([[2,3],[5,7],[11,13]])
B = np.array([[1,3],[2,1]])
C = np.array([[3,1],[4,2]])

In [3]:
# Associative
ABC = A.dot(B.dot(C))
print(ABC)

[[ 60  26]
 [145  63]
 [295 129]]


In [4]:
AB_C = A.dot(B).dot(C)
print(ABC)

[[ 60  26]
 [145  63]
 [295 129]]


In [5]:
# Distributive
D = A.dot(B+C)
E = (A.dot(B)) + (A.dot(C))

In [6]:
print(D)
print(E)

[[ 26  17]
 [ 62  41]
 [122  83]]
[[ 26  17]
 [ 62  41]
 [122  83]]


In [7]:
print(D==E)

[[ True  True]
 [ True  True]
 [ True  True]]


In [9]:
F = B.dot(C)
G = C.dot(B)

In [10]:
print(F==G)

[[False False]
 [False False]]


In [11]:
v1 = np.array([[2], [7]])
v2 = np.array([[3],[5]])

In [12]:
v1_tv2 = v1.T.dot(v2)
v2_tv1 = v2.T.dot(v1)

In [13]:
print(v1_tv2)

[[41]]


In [14]:
print(v2_tv1)

[[41]]


Note.
the inner product of matrix is:

- Associative: yes
- Distributive: yes
- Commutative: no

the inner product of vectors is:
- Associative: yes
- Distributive: yes
- Commutative: yes