<a href="https://colab.research.google.com/github/jeraldflowers/Linear-Algebra-Fundamentals/blob/main/product_vector_and_matrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
escalar = 5.679
vector = np.array([2,3])
matrix = np.array([[1,2], [3,4], [5,6]])

In [3]:
A = matrix * vector

#producto interno
B = matrix.dot(vector)

In [4]:
print(A)

[[ 2  6]
 [ 6 12]
 [10 18]]


In [5]:
print(B)

[ 8 18 28]


In [6]:
B = matrix.dot(vector)
C = np.dot(matrix, vector)
print(B)
print(C)

[ 8 18 28]
[ 8 18 28]


In [7]:
D = matrix @ vector
print(D)

[ 8 18 28]


## Between two matrix


In [8]:
A = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
B = np.array([[2,3],[5,7],[11,13]])

In [9]:
print(A.shape)

(4, 3)


In [10]:
print(B.shape)

(3, 2)


In [11]:
C = A.dot(B)

In [12]:
print(C)

[[ 45  56]
 [ 99 125]
 [153 194]
 [207 263]]


In [14]:
C.shape

(4, 2)