<a href="https://colab.research.google.com/github/jeraldflowers/Linear-Algebra-Fundamentals/blob/main/transposition_sum.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [12]:
escalar = 5.679
vector = np.array([3,4,5,6])
matrix = np.array([[1,2], [3,4], [5,6]])
tensor = np.array([
    [[1,2,3,30],[4,5,6,31],[7,8,9,32]],
    [[10,11,12,33],[13,14,15,34],[16,17,18,35]],
    [[19,20,21,36],[22,23,24,37],[25,26,27,38]]
])

In [7]:
vector_t = vector.T
print(vector_t)

[3 4 5 6]


In [8]:
matrix_t = matrix.T
print(matrix_t)

[[1 3 5]
 [2 4 6]]


In [9]:
matrix.shape

(3, 2)

In [10]:
matrix_t.shape

(2, 3)

In [13]:
tensor_t = tensor.T
print(tensor_t)

[[[ 1 10 19]
  [ 4 13 22]
  [ 7 16 25]]

 [[ 2 11 20]
  [ 5 14 23]
  [ 8 17 26]]

 [[ 3 12 21]
  [ 6 15 24]
  [ 9 18 27]]

 [[30 33 36]
  [31 34 37]
  [32 35 38]]]


In [14]:
tensor.shape

(3, 3, 4)

In [15]:
tensor_t.shape

(4, 3, 3)

In [16]:
matrix_t_t = matrix_t.T 
print(matrix_t_t)

[[1 2]
 [3 4]
 [5 6]]


# SUM

In [17]:
A = np.array([[1,2],[3,4],[5,6]])
B = np.array([[2,4],[6,8],[10,12]])
C = A + B
print(C)

[[ 3  6]
 [ 9 12]
 [15 18]]


In [18]:
D = matrix + escalar
print(D)

[[ 6.679  7.679]
 [ 8.679  9.679]
 [10.679 11.679]]


## Broadcasting

In [19]:
escalar = 5.679
vector = np.array([3,4,5])
matrix = np.array([[1,2], [3,4], [5,6]])

In [20]:
A = matrix_t + vector
print(A)

[[ 4  7 10]
 [ 5  8 11]]


In [21]:
D = matrix + np.array([[42],[42],[42]])
print(D)

[[43 44]
 [45 46]
 [47 48]]


In [22]:
v1 = np.array([1,2,3,4,5])
m1 = np.array([[1,1,1,1,1],[2,2,2,2,2],[3,3,3,3,3],[4,4,4,4,4],[5,5,5,5,5]])
sum = v1 + m1
print(sum)

[[ 2  3  4  5  6]
 [ 3  4  5  6  7]
 [ 4  5  6  7  8]
 [ 5  6  7  8  9]
 [ 6  7  8  9 10]]
